openapi: 3.1.1
security: []
servers:
    - url: '/'
info:
    title: StrainInfo - API (deprecated)
    version: 1.2.0
    license:
        name: 'CC BY 4.0'
        url: 'https://creativecommons.org/licenses/by/4.0/'
    description: >-
        # Notice

        The current stable version of the web service is v2.
        This API version is now deprecated and 
        will be replaced by version 2 in the future.

        # Privacy Policy

        We are collecting anonymized data and use it to evaluate the website performance 
        and use. You may choose to prevent this website from aggregating and analyzing 
        the actions you take here. To opt out please add 'do_not_track'
        argument to your API request.

        # Terms of use

        All information provided by this web service is carefully checked for accuracy 
        and is continuously up-dated. However, we cannot guarantee the completeness,
        the correctness and the topicality. Liability claims regarding damage
        caused by the use of any information provided, including any 
        kind of information which is incomplete or incorrect, will therefore be rejected.

        According to the verdict passed by the District Court in Hamburg the owner 
        of a website is responsible for the contents which appear in the links. 
        This can only be prevented when the owner explicitly dissociates itself to 
        these contents. We offer links to other homepages in the internet 
        and we would like to emphasize that we have no influence 
        on the contents and design of these pages. Therefore, herewith we explicitly
        dissociate ourselves from all the contents linked through our web service and that 
        we take no responsibility for these contents. This statement applies to all 
        the links offered by our web service.
paths:
    /v1/count/strains:
        $ref: paths/count_strains.yaml
    /v1/count/type_strains:
        $ref: paths/count_type_strains.yaml
    /v1/count/archive:
        $ref: paths/count_archive.yaml
    /v1/count/cultures:
        $ref: paths/count_cultures.yaml
    /v1/count/type_cultures:
        $ref: paths/count_type_cultures.yaml
    /v1/count/species:
        $ref: paths/count_species.yaml
    /v1/count/designations:
        $ref: paths/count_designations.yaml

    /v1/search/culture/str_id/{str_id}:
        $ref: paths/sea_culture_{str_id}.yaml
    /v1/search/culture/str_no/{str_no}:
        $ref: paths/sea_culture_{str_no}.yaml
    /v1/search/culture/str_des/{str_des}:
        $ref: paths/sea_culture_{str_des}.yaml
    /v1/search/culture/tax_name/{taxon_name}:
        $ref: paths/sea_culture_{taxon_name}.yaml
    /v1/search/culture/seq_acc/{seq_acc}:
        $ref: paths/sea_culture_{seq_acc}.yaml
    /v1/search/culture/brc/{brc}:
        $ref: paths/sea_culture_{brc}.yaml

    /v1/search/strain/cul_id/{cul_id}:
        $ref: paths/sea_strain_{cul_id}.yaml
    /v1/search/strain/str_no/{str_no}:
        $ref: paths/sea_strain_{str_no}.yaml
    /v1/search/strain/str_des/{str_des}:
        $ref: paths/sea_strain_{str_des}.yaml
    /v1/search/strain/tax_name/{taxon_name}:
        $ref: paths/sea_strain_{taxon_name}.yaml
    /v1/search/strain/seq_acc/{seq_acc}:
        $ref: paths/sea_strain_{seq_acc}.yaml
    /v1/search/strain/brc/{brc}:
        $ref: paths/sea_strain_{brc}.yaml

    /v1/data/strain/min/{str_id}:
        $ref: paths/data_strain_min_{str_id}.yaml
    /v1/data/strain/avg/{str_id}:
        $ref: paths/data_strain_avg_{str_id}.yaml
    /v1/data/strain/max/{str_id}:
        $ref: paths/data_strain_max_{str_id}.yaml

    /v1/data/culture/min/{cul_id}:
        $ref: paths/data_culture_min_{cul_id}.yaml
    /v1/data/culture/avg/{cul_id}:
        $ref: paths/data_culture_avg_{cul_id}.yaml
    /v1/data/culture/max/{cul_id}:
        $ref: paths/data_culture_max_{cul_id}.yaml
