version: "3"

server:
  command: "php $SERVER_RR_PHP"

http:
  address: 0.0.0.0:$BACKEND_STAGE_PORT
  middleware:
    - gzip   
  pool:
    num_workers: 4 

  gzip:
    level: 5
    min_length: 1024
    content_types:
      - "application/json"
logs:
  encoding: console 
  level: error 
  mode: "production"
