name: main

on:
    pull_request:
    push:
        branches: [main]

jobs:
    lin_lint:
        env:
            CU_HOME: /home/custom
        strategy:
            fail-fast: false
        runs-on: ubuntu-latest
        steps:
            - name: Set up Node 20
              uses: actions/setup-node@v4
              with:
                  node-version: '20'
            - name: Setup PHP with PECL extension
              uses: shivammathur/setup-php@v2
              with:
                  php-version: '8.2'
            - name: Checkout
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0
            - name: Install dependencies
              run: |
                  sudo mkdir -p $CU_HOME &&
                  sudo mkdir -p $CU_HOME/.local/bin
                  sudo chown runner -R $CU_HOME
                  sudo apt install -y curl git-lfs
            - name: lint and test
              run: |
                  make dev
                  make runChecks
